//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.Addresses = new HashSet<Address>();
            this.Documents = new HashSet<Document>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid RegistrarId { get; set; }
        public string TIN { get; set; }
        public string RCNumber { get; set; }
        public System.Guid Status { get; set; }
        public string Website { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string LastReviewBy { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public int RegistrationYear { get; set; }
    
        public virtual CorporateRegistrar CorporateRegistrar { get; set; }
        public virtual OrganisationStatu OrganisationStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
